# Load user defined packages
homeassistant:
  packages: !include_dir_named packages

# Loads default set of integrations. Do not remove.
default_config:

# Condigure push notification to  every push-capable Home Assistant Companion App
notify:
  - platform: mobile_app
    name: all_mobile_apps

# Some Crack for data junkies
recorder:
  purge_keep_days: 365

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  dashboards:
    energy-dashboard:
      mode: yaml
      filename: dashboards/energy-dashboard.yaml
      title: Energy
      icon: mdi:lightning-bolt-outline
      show_in_sidebar: true

# load automations, scripts and scenes from separate files
# I don't use this, all my automations, scripts and scenes are in packages.
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

