# Load user defined packages
homeassistant:
  packages: !include_dir_named packages

# Loads default set of integrations. Do not remove.
default_config:

# Add the history_import custom integration
history_import:

# Condigure push notification to  every push-capable Home Assistant Companion App
notify:
  - platform: mobile_app
    name: all_mobile_apps

# Some Crack for data junkies
recorder:
  purge_keep_days: 365

simple_influxdb:
  max_retries: 3
  include:
    domains:
      - sensor
      - binary_sensor
      - climate
      - cover
      - fan
      - light
      - switch
      - button
      - number
      - weather

  exclude:
    entity_globs:
      - "*.heating_test_*"

  tables:
    - name: heating
      entity_globs:
        - "*.heating_*"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  dashboards:
    energy-dashboard:
      mode: yaml
      filename: dashboards/energy/energy-dashboard.yaml
      title: Energy
      icon: mdi:lightning-bolt-outline
      show_in_sidebar: true
    home-dashboard:
      mode: yaml
      filename: dashboards/home/home-dashboard.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
    import-export-dashboard:
      mode: yaml
      filename: dashboards/import-export/import-export-dashboard.yaml
      title: Import/Export
      icon: mdi:database-outline
      show_in_sidebar: true
    test-dashboard:
      mode: yaml
      filename: dashboards/test/test-dashboard.yaml
      title: Test (yaml)
      icon: mdi:test-tube-empty
      show_in_sidebar: true

# load automations, scripts and scenes from separate files
# I don't use this, all my automations, scripts and scenes are in packages.
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Dummy SQL sensor to ensure the SQL integration is loaded
sql:
  - name: SQL Initializer
    query: "SELECT 1 AS value"
    column: "value"

logger:
  filters:
    homeassistant.util.loop:
      - "Detected blocking call to .* by integration 'aws_s3'"
    homeassistant.loader:
      - "We found a custom integration .* which has not been tested by Home Assistant.*"
  logs:
    custom_components.history_import: info
    custom_components.history_manager: info
    custom_components.simple_influxdb: info
    homeassistant.components.recorder.backup: info
    homeassistant.components.recorder.core: info

history_manager:
  short_retention:
    purge_keep_days: 14