# Overall alarm conditions for the battery charge level (sensor.battery_low_alarm)
# ans push notifications for low and critical battery states

input_number:
  battery_min_charge_warning_level:
    # the level at which the battery low warning will be triggered, as a % of full charge
    # 0 = no alarm
    name: Battery minimum charge warning level
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"

  battery_min_charge_alarm_level:
    # the level at which the battery low alarm will be triggered, as a % of full charge
    # 0 = no alarm
    name: Battery minimum charge alarm level
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"

  battery_min_charge_warning_level_off_grid:
    # the level at which the battery low warning will be triggered, as a % of full charge
    # if the system is off grid (i.e. the grid connection is down)
    # 0 = no alarm
    name: Battery minimum charge warning level (off-grid)
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"

  battery_min_charge_alarm_level_off_grid:
    # the level at which the battery low alarm will be triggered, as a % of full charge,
    # if the system is off grid (i.e. the grid connection is down)
    # 0 = no alarm
    name: Battery minimum charge alarm level (off-grid)
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"

template:
  - sensor:
      # Battery Low Alarm - currently with hard-coded thresholds
      - name: "Battery Low"
        unique_id: battery_low_alarm
        default_entity_id: sensor.battery_low_alarm
        state: >
          {% set battery = states('sensor.victron_gx_dc_battery_charge') | float(1) %}
          {% set off_grid = is_state('binary_input.victron_real_time_off_grid_alarm_internal', 'on') %}

          {% if off_grid and battery < states('input_number.battery_min_charge_alarm_level_off_grid') | float(1) %}
            alarm
          {% elif off_grid and battery < states('input_number.battery_min_charge_warning_level_off_grid') | float(1) %}
            warning
          {% elif not off_grid and battery < states('input_number.battery_min_charge_alarm_level') | float(1) %}
            alarm
          {% elif not off_grid and battery < states('input_number.battery_min_charge_warning_level') | float(1) %}
            warning
          {% else %}
            normal
          {% endif %}
        availability: >
          {{ is_number(states('sensor.victron_gx_dc_battery_charge')) }}
        icon: >
          {% set battery = states('sensor.victron_gx_dc_battery_charge') | float(1) %}
          {% set off_grid = is_state('binary_input.victron_real_time_off_grid_alarm_internal', 'on') %}

          {% if off_grid and battery < states('input_number.battery_min_charge_alarm_level_off_grid') | float(1) %}
            mdi:battery-alert
          {% elif off_grid and battery < states('input_number.battery_min_charge_warning_level_off_grid') | float(1) %}
            mdi:battery-alert
          {% elif not off_grid and battery < states('input_number.battery_min_charge_alarm_level') | float(1) %}
            mdi:battery-alert
          {% elif not off_grid and battery < states('input_number.battery_min_charge_warning_level') | float(1) %}
            mdi:battery-alert
          {% else %}
            mdi:battery-check
          {% endif %}

# Push notifications
#
#   normal -> warning: "Battery Low" notification
#   normal -> alarm: "Battery Critical" notification
#
# If the system is off grid, the "Battery Critical" notification is sent as a critical notification

automation:
  - id: battery_low_alarm_notifications
    alias: Battery low alarm notifications
    description: Sends battery warning and alarm notifications.

    triggers:
      - trigger: state
        entity_id: sensor.battery_low_alarm
        from: "normal"
        to: "warning"
        id: warning

      - trigger: state
        entity_id: sensor.battery_low_alarm
        from: "normal"
        to: "alarm"
        id: alarm

      - trigger: state
        entity_id: sensor.battery_low_alarm
        from: "warning"
        to: "alarm"
        id: alarm

    actions:
      - variables:
          notification_message: >-
            {{ 'Battery at '
               ~ (states('sensor.victron_gx_dc_battery_charge')
                  | float(0) | round(0) | int)
               ~ '%'
               ~ ('\nTarn Lodge is running off-grid.'
                  if is_state(
                    'binary_input.victron_real_time_off_grid_alarm_internal',
                    'on'
                  )
                  else '') }}

      - choose:
          # Warning: normal notification
          - conditions:
              - condition: trigger
                id: warning
            sequence:
              - action: notify.all_mobile_apps
                data:
                  title: "Battery Low"
                  message: "{{ notification_message }}"

          # Alarm while grid-connected: normal notification
          - conditions:
              - condition: trigger
                id: alarm
              - condition: state
                entity_id: binary_input.victron_real_time_off_grid_alarm_internal
                state: "off"
            sequence:
              - action: notify.all_mobile_apps
                data:
                  title: "Battery Critical"
                  message: "{{ notification_message }}"

          # Alarm while off-grid: critical notification
          - conditions:
              - condition: trigger
                id: alarm
              - condition: state
                entity_id: binary_input.victron_real_time_off_grid_alarm_internal
                state: "on"
            sequence:
              - action: notify.all_mobile_apps
                data:
                  title: "Battery Critical"
                  message: "{{ notification_message }}"
                  data:
                    # Andriod
                    ttl: 0
                    priority: high
                    channel: alarm_stream
                    # iOS
                    push:
                      sound:
                        name: default
                        critical: 1
                        volume: 1.0

    mode: queued
    max: 10
