# Because the Victron integration only polls every 30 seconds, we use our own MQTT sensors to get real-time
# power measurements for automations and triggers. 
#
# Because we can only have one MQTT server, we have to make sure that Mosquitto is configured to forward the 
# Victron MQTT messages to the local broker as follows (c0619ab7c817 is the Victron device ID):
#     topic # in 0 victron/N/ N/c0619ab7c817/
#     topic # out 0 victron/R/ R/c0619ab7c817/
#     topic # out 0 victron/W/ W/c0619ab7c817/

mqtt:
  sensor:
    # 1. Real-Time Grid Power (For instant automations/triggers)
    - name: "Real-Time Grid Power"
      unique_id: victron_real_time_grid_power
      default_entity_id: sensor.victron_real_time_grid_power
      state_topic: "victron/N/system/0/Ac/Grid/L1/Power"
      value_template: "{{ value_json.value | round(1) }}"
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      device:
        identifiers: victron_real_time_metrics
        name: "Victron Real-Time Metrics"
        manufacturer: "Victron Energy"
        model: "GX System"

    # 2. Real-Time Consumption
    - name: "Real-Time Power Consumption"
      unique_id: victron_real_time_power_consumption
      default_entity_id: sensor.victron_real_time_power_consumption
      state_topic: "victron/N/system/0/Ac/Consumption/L1/Power"
      value_template: "{{ value_json.value | round(1) }}"
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      device:
        identifiers: victron_real_time_metrics

    # 3. Real-time power to (+) or from (-) battery
    #    This is measured  on the DC side of the Victron system, so combining consumption, 
    #    solar power, grid power and battery power will NOT net to zero
    - name: "Real-Time Power To Battery"
      unique_id: victron_real_time_battery_power
      default_entity_id: sensor.victron_real_time_battery_power
      state_topic: "victron/N/system/0/Dc/Battery/Power"
      value_template: "{{ value_json.value | round(1) }}"
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      device:
        identifiers: victron_real_time_metrics

    # 4. Real-time power from the solar panels
    - name: "Real-Time Solar Power"
      unique_id: victron_real_time_solar_power
      default_entity_id: sensor.victron_real_time_solar_power
      state_topic: "victron/N/system/0/Ac/PvOnOutput/L1/Power"
      value_template: "{{ value_json.value | round(1) }}"
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      device:
        identifiers: victron_real_time_metrics

    # 5. Real-time off-grid alarm. Internal (hence _raw) because it will report "unknown"
    #    after a re-start of Home Assistant until the first MQTT message is received. 
    #    Use the sensor "victron_real_time_off_grid_alarm" for quicker on/off state.
    #    Use the "input_boolean.victron_real_time_off_grid_alarm_internal" for quicker, pure on/off state.
  binary_sensor:
    - name: "Real-Time Victron Off-Grid Alarm (raw)"
      unique_id: victron_real_time_off_grid_alarm_raw
      default_entity_id: binary_sensor.victron_real_time_off_grid_alarm_raw
      device_class: problem
      state_topic: "victron/N/vebus/275/Ac/ActiveIn/Connected"
      value_template: "{{ value_json.value }}"
      payload_on: "0"
      payload_off: "1"
      device:
        identifiers: victron_real_time_metrics


input_boolean:
    # 5b. Real-time off-grid alarm - either "on" (alarm) or "off" (normal).
    #     If the raw sensor is "unknown" or "unavailable", we keep the previous state.
    #     This is an internal input set by a trigger to avoid the "unknown" state after
    #     a restart of Home Assistant until the first MQTT message is received.
  victron_real_time_off_grid_alarm_internal:
    name: "Real-Time Victron Off-Grid Alarm"

automation:
  - alias: "Victron MQTT Keep-Alive"
    id: victron_mqtt_keep_alive
    description: "Pings the Victron GX local broker via the Mosquitto bridge to maintain the real-time data stream."
    triggers:
      - trigger: time_pattern
        seconds: "/30"
    condition: []
    action:
      - action: mqtt.publish
        data:
          topic: "victron/R/keepalive"
          payload: "{}"
    mode: single

  - id: victron_real_time_off_grid_alarm_update
    alias: "Update Real-Time Victron Off-Grid Alarm"
    mode: restart
    triggers:
      # Anything -> on
      - trigger: state
        entity_id: binary_sensor.victron_real_time_off_grid_alarm_raw
        to: "on"
        id: "on"
      # Anything -> off
      - trigger: state
        entity_id: binary_sensor.victron_real_time_off_grid_alarm_raw
        to: "off"
        id: "off"
    actions:
      - choose:
          - conditions: "{{ trigger.id == 'on' }}"
            sequence:
              - action: input_boolean.turn_on
                target:
                  entity_id: input_boolean.victron_real_time_off_grid_alarm_internal

          - conditions: "{{ trigger.id == 'off' }}"
            sequence:
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.victron_real_time_off_grid_alarm_internal

template:
    # 5c. Real-time off-grid alarm - either "on" (alarm) or "off" (normal).
    #     If the raw sensor is "unavailable", we keep the previous state.
    #     NB - it may still be "unavailable" after a restart, but will
    #     take its proper value more quickly than waiting for the first MQTT message
    #     to arrive.
  - binary_sensor:
    - name: "Real-Time Victron Off-Grid Alarm"
      unique_id: victron_real_time_off_grid_alarm
      default_entity_id: binary_sensor.victron_real_time_off_grid_alarm
      device_class: problem
      state: >
        {{ is_state('input_boolean.victron_real_time_off_grid_alarm_internal', 'on') }}
      # This sensor reflects the input_boolean state above so existing
      # code expecting a sensor did not break

  - sensor:
    # 6. AC-side estimate of battery power
    #    See (3) above - we only have the DC battery power measurement, so we calculate the AC-side battery power as:
    #    battery_power = grid_power + solar_power - consumption_power
    - name: "Real-Time Power To Battery (calculated)"
      unique_id: victron_real_time_battery_power_calculated
      default_entity_id: sensor.victron_real_time_battery_power_calculated
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      availability: >
        {{
          is_number(states('sensor.victron_real_time_grid_power'))
          and is_number(states('sensor.victron_real_time_solar_power'))
          and is_number(states('sensor.victron_real_time_power_consumption'))
        }}
      state: >
        {{
          (
            (states('sensor.victron_real_time_grid_power') | float)
            + (states('sensor.victron_real_time_solar_power') | float)
            - (states('sensor.victron_real_time_power_consumption') | float)
          ) 
        }}

      # 6. Calculated battery power minus measured DC battery power
      # Zero = perfect agreement
      # Positive = calculated charging power is higher
    - name: "Real-Time Power Tracking Error"
      unique_id: victron_real_time_power_tracking_error
      default_entity_id: sensor.victron_real_time_power_tracking_error
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      availability: >
        {{
          is_number(states('sensor.victron_real_time_grid_power'))
          and is_number(states('sensor.victron_real_time_solar_power'))
          and is_number(states('sensor.victron_real_time_power_consumption'))
          and is_number(states('sensor.victron_real_time_battery_power'))
        }}
      state: >
        {{
          (
            (states('sensor.victron_real_time_grid_power') | float)
            + (states('sensor.victron_real_time_solar_power') | float)
            - (states('sensor.victron_real_time_power_consumption') | float)
            - (states('sensor.victron_real_time_battery_power') | float)
          )
        }}

      # 6. Calculated battery power minus measured DC battery power
      # Zero = perfect agreement
      # Positive = calculated charging power is higher
    - name: "Real-Time Power Untracked"
      unique_id: victron_real_time_power_untracked
      default_entity_id: sensor.victron_real_time_power_untracked
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      availability: >
        {{
          is_number(states('sensor.victron_real_time_grid_power'))
          and is_number(states('sensor.victron_real_time_solar_power'))
          and is_number(states('sensor.victron_real_time_power_consumption'))
          and is_number(states('sensor.victron_real_time_battery_power_calculated'))
          and is_number(states('sensor.real_time_power_aircon'))
        }}
      state: >
        {{
          (
            (states('sensor.victron_real_time_grid_power') | float)
            + (states('sensor.victron_real_time_solar_power') | float)
            - (states('sensor.victron_real_time_power_consumption') | float)
            - (states('sensor.victron_real_time_battery_power_calculated') | float)
            - (states('sensor.real_time_power_aircon') | float)
          )
        }}

      # 7a. Power used by airconditioning units
    - name: "Real-Time A/C Power"
      unique_id: real_time_power_aircon
      default_entity_id: sensor.real_time_power_aircon
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      availability: >
        {{
          is_number(states('sensor.ac_bedroom_power'))
          and is_number(states('sensor.ac_cinema_power'))
        }}
      state: >
        {{
          (
            (states('sensor.ac_bedroom_power') | float)
            + (states('sensor.ac_cinema_power') | float)
          )
        }}

input_datetime:
  energy_chart_day:
    name: Day for Energy Chart
    has_date: true
    has_time: false
  energy_chart_range_start:
    name: Start date for Energy Chart
    has_date: true
    has_time: false
  energy_chart_range_end:
    name: End date for Energy Chart
    has_date: true
    has_time: false

recorder:
  exclude:
    entities:
      - sensor.victron_real_time_power_tracking_error
      - sensor.victron_real_time_battery_power_calculated
      - sensor.victron_real_time_power_consumption
      - sensor.victron_real_time_grid_power
      - sensor.victron_real_time_solar_power
      - sensor.victron_real_time_power_untracked
      - sensor.victron_real_time_battery_power
      - sensor.victron_real_time_battery_power_inv
      - sensor.victron_real_time_power_aicon
      - input_datetime.energy_chart_day
      - input_datetime.energy_chart_range_start
      - input_datetime.energy_chart_range_end
    entity_globs:
      - "sensor.victron_multiplus_ii_0_line_*"    # duplicate 'device 0' sensors

history_manager:
  short_retention:
    entities:
      - sensor.gx_device_gx_system_heartbeat
      - automation.victron_mqtt_keep_alive
    entity_globs:
      - "*.victron_multiplus_ii*"
      - "*.electricity_victron_multiplus_ii*"
      - "*.victron_gx*"
      - "*.electricity_victron_gx*"
      - "*.pylontech_battery*"
      - "*.electricity_pylontech_battery*"
      - "*.pv_inverter_on_output*"
      - "button.gx_device*"

simple_influxdb:
  exclude:
    entities:
      - sensor.gx_device_gx_system_heartbeat
      - automation.victron_mqtt_keep_alive
    entity_globs:
      - "*.victron_multiplus_ii*"
      - "*.electricity_victron_multiplus_ii*"
      - "*.victron_gx*"
      - "*.electricity_victron_gx*"
      - "*.pylontech_battery*"
      - "*.electricity_pylontech_battery*"
      - "*.pv_inverter_on_output*"
      - "button.gx_device*"
