sensor:
  - platform: integration
    source: sensor.opendtu_4b0618_ac_power
    name: Solar Energy Total (Hoymiles)
    unique_id: solar_energy_total
    unit_prefix: k
    unit_time: h
    method: trapezoidal
    round: 3
    max_sub_interval:
      minutes: 1

utility_meter:
  solar_production_today:
    source: sensor.solar_energy_total
    name: Solar Production Today (Hoymiles)
    unique_id: solar_production_today
    cycle: daily
    periodically_resetting: false

template:
  - sensor:
      - name: "Dynamic Power Limiter Total Upper Power Limit"
        unique_id: dynamic_power_limiter_total_upper_power_limit_sensor
        default_entity_id: sensor.dynamic_power_limiter_total_upper_power_limit
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        state: >
          {{ states('number.dynamic_power_limiter_total_upper_power_limit') | float }}
        availability: >
          {{ is_number(states('number.dynamic_power_limiter_total_upper_power_limit')) }}